name: Create PDF slides

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed
  workflow_dispatch:
jobs:
  deploy-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get GH pages URL
        run: ruby .github/scripts/github_pages.ru | xargs -I{} echo '::set-output name=URL::{}'
        id: gh-pages-url
      - name: Produce PDF
        run: npx decktape automatic ${{ steps.gh-pages-url.outputs.URL }} slides.pdf
      - name: Tag From date
        run: echo $(date +'%Y.%m.%d-%H:%M') | xargs -I{}  echo '::set-output name=TAG::{}'  
        id: tag-from-date
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.pdf"
          draft: false
          tag_name: ${{ steps.tag-from-date.outputs.TAG}}